stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3-jdk-8
          shellScript: |-
            mvn clean install -Dmaven.test.skip=true
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: notebook:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml